truncate table Users
truncate table Vehicles

--password generated by SecurityUtils.encryptPassword
set identity_insert Users on
insert Users(id, loginName, name, password, regTime, gid)
select 1, '111', 'aaa', '96E79218965EB72C92A549DD5A330112', '2010-1-1', 1
union select 2, '222', 'bbb', 'E3CEB5881A0A1FDAAD01296D7554868D', '2010-1-1', 2
set identity_insert Users off

insert Accesses(id, name)
select 1, 'acc_a'
union select 2, 'acc_b'

insert Vehicles(uid, status, brand, licensePlate)
select 2, 0, 'H2IK', '222'
